### ISSUE TITLE
Silent error when `uploads` directory is not created

### ISSUE THREAD

**Issue by noah-yoshida** [pbui/yldme#7]
If the `uploads` directory does not exist in the project root directory, then pasting files will silently fail (file is never created, but no error message is thrown)

**Comment by pbui** [comment]
I believe @AndroidKitKat has a fix for this in his new configuration code (it will create the uploads directory on startup).

We'll keep it open for now.

**Comment by noah-yoshida** [comment]
Ok, I added a check in the code to create it, but if he got it fixed then I'll hold off on that

**Comment by AndroidKitKat** [comment]
Yeah I fixed that. Trying to fix something else right now and then that should get pushed with the first batch of config stuff.

**Comment by AndroidKitKat** [comment]
Should be fixed
